### ISSUE TITLE
Auto activate intelephense if license key is available

### ISSUE THREAD

**Issue by strausmann** [apolopena/gitpod-laravel-starter#165]
## Problem this feature will solve

every time you start a new GitPod you have to enter your license number for intelephense again. According to the FAQ of intelephense you can create the license in the file $HOME/intelephense/licence.txt and intelephense will be activated automatically.

## Proposed Solution

Store the license as GitPod Env, e.g. with the KEY "INTELEPHENSE_LICENSEKEY". If this ENV is present at the start of the GitPod, it should be written into the file $HOME/intelephense/licence.txt.

**Comment by apolopena** [comment]
Is there is a free key we can use for QA?
Do you know if the key is checked on a workspace restart? If so we will need to persist `$HOME/intelephense/licence.txt`.

**Comment by strausmann** [comment]
No a free Key is not available, but I have a Key and can do the QA. I think the Key will only be imported. When i enter the Key via VSCode I cant find the Key here $HOME/intelephense/licence.txt

**Comment by apolopena** [comment]
> No a free Key is not available, but I have a Key and can do the QA. I think the Key will only be imported. When i enter the Key via VSCode I cant find the Key here $HOME/intelephense/licence.txt

It looks like `$HOME/intelephense/licence.txt` has to be generated manually. It also seems like `$HOME/intelephense/licence.txt` would need to exist before the gitpod vscode container is loaded. I will give you a code snippet and a test plan to try and we can figure it out.

Lastly as of the time of writing this I do belive that without the expiremental beta 'backup workspace' gitpod option turned on by the gitpod admins any files/directories in `$HOME would need to be manually backed up after a workspace stops.

I tend to lean away from adding functionality into the core files that I cannot test. The automagic Intellephense key file could be implemented per project in [init-project.sh](https://github.com/apolopena/gitpod-laravel-starter/blob/main/.gp/bash/init-project.sh). This is exactly the kind of thing [init-project.sh](https://github.com/apolopena/gitpod-laravel-starter/blob/main/.gp/bash/init-project.sh) was designed for. This way if Intellephense changes how their key should be implmented then the core files wont  need to be changed to reflect that.
Either way though if you find that adding a code snippet to init-project.sh](https://github.com/apolopena/gitpod-laravel-starter/blob/main/.gp/bash/init-project.sh) for each project you build to be too cumbersome we could put it in the core files if it is tested well since it is pretty simple functionality after all and it is unlikely that Intelliphense would change how to implement their key.

**Comment by apolopena** [comment]
@strausmann 
**The fix for now ( I wrote this blind but it should work )**:
1. Set the environment varaible `INTELEPHENSE_LICENSEKEY` in your Gitpod dashboard (settings). Set the value to your Intelliphense key.
2. Put the below code block in a fresh project built from your fork in `.gp/bash/init-project.sh` push the change to remote, build the workspace and see if Intelliphense recognizes the dynamically generated `$HOME/intelephense/licence.txt` file. 
 ```bash
if [[ -n $INTELLIPHENSE_LICENSEKEY ]]; then
  mkdir -p "$HOME/intelliphense"
  echo "$INTELLIPHENSE_LICENSEKEY" > "$HOME/intelliphense/license.txt"
fi
```
3. Verify that your environment variable set in step 1 is present by running: `echo "$INTELEPHENSE_LICENSEKEY"`
4. Once step 3 is verified, verify that `$HOME/intelephense/licence.txt` was indeed generated  and contains a single value equal to the Intelliphense license key that you set in the Gitpod dashboard by running the below command after the terminal opens in the gitpod VS-Code IDE.
```bash
cat ~/intelliphense/license.txt
```

 Let me know the results of 1, 2, 3 and 4 and then we will proceed from there.

**Comment by strausmann** [comment]
Dear @apolopena 

I have now tried the whole thing once. Had been somewhat problematic.

Shortly to the info, in your samples the paths and the name of the licence.txt were not correct. Therefore here again my code block with which it worked.

Using the code block in the [init-project.sh](https://github.com/strausmann/gitpod-laravel-starter/blob/intelephense/.gp/bash/init-project.sh) is unfortunately way too late if you don't use a prebuild. Therefore it makes more sense to use the block in the [before-tasks.sh](https://github.com/strausmann/gitpod-laravel-starter/blob/intelephense/.gp/bash/before-tasks.sh). Because the license file is deleted after a restart of the workspace.

Why too late? If the user opens a PHP file before the init-project.sh has run, the extension will be loaded and the license file will be checked, if it exists. But since this may not have been created yet, because init-project.sh runs really late, it will not work on images that have not been prebuilt with a prebuild.

```php
if [[ -n $INTELEPHENSE_LICENSEKEY ]]; then
log "Notice: Intelephense Licensekey found, push to $HOME/intelephense/licence.txt"
 mkdir -p "$HOME/intelephense"
 echo "$INTELEPHENSE_LICENSEKEY" > "$HOME/intelephense/licence.txt"
fi
```

![image](https://user-images.githubusercontent.com/4519228/149312761-3e5e2323-4dd3-4a0b-9da3-78694531ac5a.png)


![image](https://user-images.githubusercontent.com/4519228/149312713-07ee5406-7919-4116-979e-a36e86004671.png)

**Comment by apolopena** [comment]
Sounds fair., thank for explaining the timing and results of your tests. I will work on integrating this into the development branch. Thank you.

**Comment by apolopena** [comment]
@strausmann ready to test in the `development` branch

**Comment by strausmann** [comment]
Successfully tested. License was detected and activated the first time a PHP file was opened.
